const ProtocolInitialState = {
    id: undefined,
    currentBlock: 0,
    init: false,
    epoch: undefined,
    totalSwaps: '0',
    totalUsers: '0',
    totalNuggs: '0',
    totalItems: '0',
    totalItemSwaps: '0',
    genesisBlock: '0',
    interval: '0',
    xnuggTotalSupply: '0',
    xnuggTotalEth: '0',
    nuggftTotalEth: '0',
    nuggftStakedUsdPerShare: '0',
    nuggftStakedUsd: '0',
    nuggftStakedEthPerShare: '0',
    nuggftStakedEth: '0',
    nuggftStakedShares: '0',
    priceUsdcWeth: '0',
    priceWethXnugg: '0',
    tvlEth: '0',
    tvlUsd: '0',
    defaultActiveNugg: undefined,
    activeNuggs: [],
    activeItems: [],
    error: undefined,
    success: undefined,
    loading: false,
    xnuggUser: undefined,
    nuggftUser: undefined,
    nullUser: undefined,
};

export default ProtocolInitialState;
